// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSpzm5dCFb_A3kQFHKhL4aQI5ra-eVneI',
    appId: '1:567129524819:web:f27b7f9a71e8a5a8e7d4a6',
    messagingSenderId: '567129524819',
    projectId: 'money-9a2b4',
    authDomain: 'money-9a2b4.firebaseapp.com',
    storageBucket: 'money-9a2b4.appspot.com',
    measurementId: 'G-JM8713Q7GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5NhcXVN12esnj4K1RpGcXCDoMte_mgI',
    appId: '1:567129524819:android:5da7626576a05c78e7d4a6',
    messagingSenderId: '567129524819',
    projectId: 'money-9a2b4',
    storageBucket: 'money-9a2b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgx2Ix3mrHABplpAPNbiMbACafFQKVBJc',
    appId: '1:567129524819:ios:9b10abb44bd0f272e7d4a6',
    messagingSenderId: '567129524819',
    projectId: 'money-9a2b4',
    storageBucket: 'money-9a2b4.appspot.com',
    iosClientId: '567129524819-v20drnf6pn6c04ri006t2keege4gp4c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgx2Ix3mrHABplpAPNbiMbACafFQKVBJc',
    appId: '1:567129524819:ios:5ef805f1e2e8584ee7d4a6',
    messagingSenderId: '567129524819',
    projectId: 'money-9a2b4',
    storageBucket: 'money-9a2b4.appspot.com',
    iosClientId: '567129524819-amih81j6p4pi383ap2r5si6paoo6tfac.apps.googleusercontent.com',
    iosBundleId: 'com.example.money.RunnerTests',
  );
}
