// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLugDD7pZyeO9VEDE0DdhBK6JTYnOdsk',
    appId: '1:1084758301193:web:08ddb022413d967273f6d8',
    messagingSenderId: '1084758301193',
    projectId: 'moneymanager-bfe11',
    authDomain: 'moneymanager-bfe11.firebaseapp.com',
    storageBucket: 'moneymanager-bfe11.appspot.com',
    measurementId: 'G-CE06GJ28R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTUNFSha_uH79YbLqIeHSzf8tlvfNyl0',
    appId: '1:1084758301193:android:efdd83fdf92e9cc273f6d8',
    messagingSenderId: '1084758301193',
    projectId: 'moneymanager-bfe11',
    storageBucket: 'moneymanager-bfe11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9dBQi53eeGM0rV3bCtK8n3ELNvPAct6Q',
    appId: '1:1084758301193:ios:38f0d537a085d3e273f6d8',
    messagingSenderId: '1084758301193',
    projectId: 'moneymanager-bfe11',
    storageBucket: 'moneymanager-bfe11.appspot.com',
    iosBundleId: 'com.example.moneymanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9dBQi53eeGM0rV3bCtK8n3ELNvPAct6Q',
    appId: '1:1084758301193:ios:2c434d8314452a0673f6d8',
    messagingSenderId: '1084758301193',
    projectId: 'moneymanager-bfe11',
    storageBucket: 'moneymanager-bfe11.appspot.com',
    iosBundleId: 'com.example.moneymanager.RunnerTests',
  );
}
